/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthKiteCallbackRouteImport } from './routes/auth.kite.callback'

const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthKiteCallbackRoute = AuthKiteCallbackRouteImport.update({
  id: '/auth/kite/callback',
  path: '/auth/kite/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/holdings': typeof HoldingsRoute
  '/login': typeof LoginRoute
  '/stream': typeof StreamRoute
  '/auth/kite/callback': typeof AuthKiteCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/holdings': typeof HoldingsRoute
  '/login': typeof LoginRoute
  '/stream': typeof StreamRoute
  '/auth/kite/callback': typeof AuthKiteCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/holdings': typeof HoldingsRoute
  '/login': typeof LoginRoute
  '/stream': typeof StreamRoute
  '/auth/kite/callback': typeof AuthKiteCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/holdings' | '/login' | '/stream' | '/auth/kite/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/holdings' | '/login' | '/stream' | '/auth/kite/callback'
  id:
    | '__root__'
    | '/'
    | '/holdings'
    | '/login'
    | '/stream'
    | '/auth/kite/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HoldingsRoute: typeof HoldingsRoute
  LoginRoute: typeof LoginRoute
  StreamRoute: typeof StreamRoute
  AuthKiteCallbackRoute: typeof AuthKiteCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/kite/callback': {
      id: '/auth/kite/callback'
      path: '/auth/kite/callback'
      fullPath: '/auth/kite/callback'
      preLoaderRoute: typeof AuthKiteCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HoldingsRoute: HoldingsRoute,
  LoginRoute: LoginRoute,
  StreamRoute: StreamRoute,
  AuthKiteCallbackRoute: AuthKiteCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
